package cn.kanmars.dao.base;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import org.hibernate.criterion.SimpleExpression;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public interface IQueryObj {

    /**
     * Execute a query.
     * @param query a query expressed in Hibernate's query language
     * @return a distinct list of instances (or arrays of instances)
     */
    public abstract java.util.List find(String query);
    
    /**
	 * 执行Criteria的动态查询
	 * 返回一个Object[3],其中Object[0]为List<Object[]>或者List&lt;Object&gt;对象,Object[1]为pageSize,Object[2]为pageNum
	 * 性能较findByNamedQuery(final String name, final int begin,final int count)好，实时查询没有缓存
	 * @param oneClass	获得的类
	 * @param simpleExpression	Restrictions生成的实例List
	 * @param pageSize	每页数量
	 * @param pageNum	开始页数
	 * @return
	 */
    public abstract Object[] findByCriteria(Class oneClass,List<SimpleExpression> simpleExpression,int pageSize,int pageNum);

    /**
     * Return all objects related to the implementation of this DAO with no filter.
     */
    public abstract java.util.List findAll();

    /**
     * Obtain an instance of Query for a named query string defined in the mapping file.
     * @param name the name of a query defined externally
     * @return Query
     */
    public abstract java.util.List findByNamedQuery(String name);

    public abstract java.util.List findByNamedQuery(final String name, final int begin, final int count);

    /**
     * Obtain an instance of Query for a named query string defined in the mapping file.
     * Use the parameters given.
     * @param name the name of a query defined externally
     * @param params the parameter Map
     * @return Query
     */
    public abstract java.util.List findByNamedQuery(final String name, final Map params);

    public abstract java.util.List findByNamedQuery(final String name, final Map params, final int begin, final int count);


    /**
     * Obtain an instance of Query for a named query string defined in the mapping file.
     * Use the parameters given.
     * @param name the name of a query defined externally
     * @param params the parameter array
     * @return Query
     */
    public abstract java.util.List findByNamedQuery(final String name, final Serializable[] params);

    public abstract java.util.List findByNamedQuery(final String name, final Serializable[] params, final int begin, final int count);
}
